### ISSUE TITLE
EQ.js and React

### ISSUE THREAD

**Issue by pborrego** [joeybaker/react-element-query#1]
In the readme it is mentioned that "eq.js does a good job, but it doesn't play nicely with React". Can this be explained as to why eq.js does not play nicely with React. Does eq.js actually break React (i.e., causes javascript errors) or does React remove the data attributes that eq.js is setting/need?

I am just curious since I am not really finding any one else talking about issues with eq.js and React (yet at least). Are there any posts or articles that can be added to explain the problem?

**Comment by joeybaker** [comment]
I don't remember all the details, but basically, EQ.js will affect the DOM outside of React's render pipeline. That means breaks React's virtual DOM model :\

**Comment by pborrego** [comment]
Sorry I'm still new with React. If the virtual DOM is broken does that mean React will not work as expected or would the virtual DOM start overwriting the DOM that had changed outside of the render pipeline?

**Comment by joeybaker** [comment]
Both :)

**Comment by joeybaker** [comment]
@pborrego I'm going to close this. Please re-open if you have other questions.
