### ISSUE TITLE
default prop doesn't work

### ISSUE THREAD

**Issue by digitaldho** [joeybaker/react-element-query#10]
Adding default doesn't seem to do anything.  I still only get the class name added for 2 break points. Am I using this wrong?

ElementQuery sizes={[{name: 'layout-desktop', width: 1024}, {name: 'layout-tablet', width: 768}]} default='layout-mobile'>

	<div styleName='standard'>

		{content}

	</div>

/ElementQuery>

**Comment by joeybaker** [comment]
Add `layout-mobile` to your array of `sizes`

**Comment by joeybaker** [comment]
@digitaldho I'm going to close this issue. Feel free to comment back if you still need help.
