### ISSUE TITLE
Refresh child component class programatically

### ISSUE THREAD

**Issue by ingro** [joeybaker/react-element-query#3]
Hello and thanks for your library. 
I have a problem anyway: I need to re-apply the size class on the child at a button toggle, not on window resize. How could I achieve this? It is possible with this library?

Thanks.

**Comment by joeybaker** [comment]
Hmmm… that seems out of scope for this library. Can you just do that with an `onClick` handler on the button?

**Comment by ingro** [comment]
Well you're right, I was over-thinking it. I could easily apply manually the class to the child element on button click, sorry for opening this and thanks for the reply!

**Comment by joeybaker** [comment]
:)
