### ISSUE TITLE
Consider using cross-env for NODE_ENV 

### ISSUE THREAD

**Issue by sag1v** [joeybaker/react-element-query#48]
Hi, I'm using windows and when i try to run some of the scripts (the `build` for example) i get errors because `NODE_ENV=production` is not a valid command on windows.
There is a simple solution which can work on all platforms - [cross-env](https://www.npmjs.com/package/cross-env).
Just install
`npm install --save-dev cross-env`
And then use it like this:
`"build": "cross-env NODE_ENV=production && babel src --out-dir dist",`

Hope it helps :)

**Comment by joeybaker** [comment]
I'd happily take a PR!

**Comment by sag1v** [comment]
cool #49

**Comment by joeybaker** [comment]
Closed by https://github.com/joeybaker/react-element-query/pull/49
