### ISSUE TITLE
Not updating correctly with BEM syntax class names

### ISSUE THREAD

**Issue by davidspiess** [joeybaker/react-element-query#6]
I have following class names defined

```jsx
<ElementQuery
    sizes={[
        {name: 'Bs-Widget--large', width: 700},
        {name: 'Bs-Widget--small', width: 400}
    ]}
>
    <div className="Bs-Widget"></div>
</ElementQuery>
```
It creates correctly the DOM node
```html
<div class="Bs-Widget Bs-Widget--large"></div>
```

But after that it does not update on window resize.
I think there is a problem when there are multiple classes beginning with the same name.
I tried some variations to give you a better idea

`Bs-Widget Bs-Widget--large` :negative_squared_cross_mark: 
`Bs-Widgett Bs-Widget--large` :white_check_mark: 
`Lala Bs-Widget--large` :white_check_mark: 
`Bs-Widget--large` :white_check_mark:

**Comment by davidspiess** [comment]
My bad. There was a fixed with on the `Bs-Widget` container, which of course let to wrong results.

**Comment by joeybaker** [comment]
Glad you got it sorted out!
